service: default
runtime: nodejs10
#handlers:
#  - url: /
#    http_headers:
#      Access-Control-Allow-Origin: *
handlers:
  - url: /request-token
    script: auto
    http_headers:
      Access-Control-Allow-Origin: https://controlify.noodlewrecker.xyz/