service: default
runtime: nodejs10
#handlers:
#  - url: /
#    http_headers:
#      Access-Control-Allow-Origin: *
handlers:
  - url: /request-token
    static_dir: request-token/
    http_headers:
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "*"
      Access-Control-Allow-Headers: "*"
  - url: /
    static_dir: /
    http_headers:
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "*"
      Access-Control-Allow-Headers: "*"